### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Erebu5** [zfox23/colorSortedImageGrid#2]
Hello again!

Thank you so much for your previous reply. After changing directories, it's now stating: TypeError: Jimp.read is not a function

Copied Terminal contents for you.

Thank you!

Detecting number of columns and number of rows in output image...
Done!
Number of input images: 91
Number of columns: 10
Number of rows: 10

Processing all images...
Processing `000249150010.jpg`...
Processing `000249150011.jpg`...
Processing `000249150012.jpg`...
Processing `000249150014.jpg`...
Processing `000249150015.jpg`...
Processing `000249150018.jpg`...
Processing `000249150019.jpg`...
Processing `000249150021.jpg`...
Processing `000249150023.jpg`...
Processing `000249150024.jpg`...
Processing `000249150025.jpg`...
Processing `000249150026.jpg`...
Processing `000249150027.jpg`...
Processing `000249150029.jpg`...
Processing `000249150031.jpg`...
Processing `000249150035.jpg`...
Processing `000249150037.jpg`...
Processing `000378870001.jpg`...
Processing `000378870002.jpg`...
Processing `000378870003.jpg`...
Processing `000378870004.jpg`...
Processing `000378870005.jpg`...
Processing `000378870006.jpg`...
Processing `000378870007.jpg`...
Processing `000378870008.jpg`...
Processing `000378870009.jpg`...
Processing `000378870010.jpg`...
Processing `000378870011.jpg`...
Processing `000378870012.jpg`...
Processing `000378870013.jpg`...
Processing `000378870014.jpg`...
Processing `000378870015.jpg`...
Processing `000378870016.jpg`...
Processing `000378870017.jpg`...
Processing `000378870018.jpg`...
Processing `000378870019.jpg`...
Processing `000378870020.jpg`...
Processing `000378870021.jpg`...
Processing `000378870022.jpg`...
Processing `000378870023.jpg`...
Processing `000378870024.jpg`...
Processing `000378870025.jpg`...
Processing `000378870026.jpg`...
Processing `000378870027.jpg`...
Processing `000378870028.jpg`...
Processing `000378870029.jpg`...
Processing `000378870030.jpg`...
Processing `000378870031.jpg`...
Processing `000378870032.jpg`...
Processing `000378870033.jpg`...
Processing `000378870034.jpg`...
Processing `000378870035.jpg`...
Processing `000378870036.jpg`...
Processing `000378870037.jpg`...
Processing `000495060001.jpg`...
Processing `000495060002.jpg`...
Processing `000495060003.jpg`...
Processing `000495060004.jpg`...
Processing `000495060005.jpg`...
Processing `000495060006.jpg`...
Processing `000495060007.jpg`...
Processing `000495060008.jpg`...
Processing `000495060009.jpg`...
Processing `000495060010.jpg`...
Processing `000495060011.jpg`...
Processing `000495060012.jpg`...
Processing `000495060013.jpg`...
Processing `000495060014.jpg`...
Processing `000495060015.jpg`...
Processing `000495060016.jpg`...
Processing `000495060017.jpg`...
Processing `000495060018.jpg`...
Processing `000495060019.jpg`...
Processing `000495060020.jpg`...
Processing `000495060021.jpg`...
Processing `000495060022.jpg`...
Processing `000495060023.jpg`...
Processing `000495060024.jpg`...
Processing `000495060025.jpg`...
Processing `000495060026.jpg`...
Processing `000495060027.jpg`...
Processing `000495060028.jpg`...
Processing `000495060029.jpg`...
Processing `000495060030.jpg`...
Processing `000495060031.jpg`...
Processing `000495060032.jpg`...
Processing `000495060033.jpg`...
Processing `000495060034.jpg`...
Processing `000495060035.jpg`...
Processing `000495060036.jpg`...
Processing `000495060037.jpg`...
**/Users/mol3cul3/Desktop/colorSortedImageGrid-1.1.1/index.js:162
            Jimp.read(`${argv.inputDirectory}/${imageFilename}`)
                 ^

TypeError: Jimp.read is not a function
    at /Users/mol3cul3/Desktop/colorSortedImageGrid-1.1.1/index.js:162:18
    at Array.forEach (<anonymous>)
    at /Users/mol3cul3/Desktop/colorSortedImageGrid-1.1.1/index.js:159:24
    at new Promise (<anonymous>)
    at processImages (/Users/mol3cul3/Desktop/colorSortedImageGrid-1.1.1/index.js:150:12)
    at createColorSortedImageGrid (/Users/mol3cul3/Desktop/colorSortedImageGrid-1.1.1/index.js:355:5)
    at Object.<anonymous> (/Users/mol3cul3/Desktop/colorSortedImageGrid-1.1.1/index.js:439:1)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)**

**Comment by zfox23** [comment]
Aha! Did you run `npm i` before trying `node index.js` ? If not, try running `npm i` to install the script's dependencies first.

**Comment by Erebu5** [comment]
Ran `npm i` then `node index.js` again, still got the same type error.

I'm so sorry for all the bother!

/Users/mol3cul3/Desktop/colorSortedImageGrid-1.1.1/index.js:162
            Jimp.read(`${argv.inputDirectory}/${imageFilename}`)
                 ^

TypeError: Jimp.read is not a function
    at /Users/mol3cul3/Desktop/colorSortedImageGrid-1.1.1/index.js:162:18
    at Array.forEach (<anonymous>)
    at /Users/mol3cul3/Desktop/colorSortedImageGrid-1.1.1/index.js:159:24
    at new Promise (<anonymous>)
    at processImages (/Users/mol3cul3/Desktop/colorSortedImageGrid-1.1.1/index.js:150:12)
    at createColorSortedImageGrid (/Users/mol3cul3/Desktop/colorSortedImageGrid-1.1.1/index.js:355:5)
    at Object.<anonymous> (/Users/mol3cul3/Desktop/colorSortedImageGrid-1.1.1/index.js:439:1)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)

![Screenshot 2024-11-30 at 16 24 40](https://github.com/user-attachments/assets/0d59f120-8fe6-4e17-8746-b1e655f4cd09)

**Comment by zfox23** [comment]
How strange! Give me a moment to try to reproduce this on my Mac.

**Comment by Erebu5** [comment]
Okay, sounds good!

**Comment by zfox23** [comment]
I can only reproduce this error when the latest version of Jimp is installed. Can you please try deleting your `node_modules` directory, re-running `npm i`, and retrying `node index.js`?

I should update the script dependencies to the latest version, and I'll do that at some point...

**Comment by Erebu5** [comment]
Hi again! I deleted the node_modules directory and re-ran 'npm i' followed by 'node index.js' as you said. Still throwing the same type error. That pesky Jimp. 

Anywho! Really appreciate you taking the time to troubleshoot and walking me through it.


/Users/mol3cul3/Desktop/colorSortedImageGrid-1.1.1/index.js:162
            Jimp.read(`${argv.inputDirectory}/${imageFilename}`)
                 ^

TypeError: Jimp.read is not a function
    at /Users/mol3cul3/Desktop/colorSortedImageGrid-1.1.1/index.js:162:18
    at Array.forEach (<anonymous>)
    at /Users/mol3cul3/Desktop/colorSortedImageGrid-1.1.1/index.js:159:24
    at new Promise (<anonymous>)
    at processImages (/Users/mol3cul3/Desktop/colorSortedImageGrid-1.1.1/index.js:150:12)
    at createColorSortedImageGrid (/Users/mol3cul3/Desktop/colorSortedImageGrid-1.1.1/index.js:355:5)
    at Object.<anonymous> (/Users/mol3cul3/Desktop/colorSortedImageGrid-1.1.1/index.js:439:1)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)

**Comment by zfox23** [comment]
How strange! Well - I have pushed a change to `main` which updates all script dependencies (including Jimp) and fixes issues associated with that upgrade.

It's not tested enough for me to feel comfortable making a new release with that change, but it might fix your issue.

Please try:
1. Re-downloading the latest version of the code from `main` [via this link](https://github.com/zfox23/colorSortedImageGrid/archive/refs/heads/main.zip)
2. Unzipping the code into a new folder
3. Re-running `npm i` from that new folder
4. Running `node index.js` from that new folder

**Comment by Erebu5** [comment]
Hi, so sorry for the delay. Haven't had a chance to test it until now. It works!!!

Thank you so so so much for your time and help. Excited to spend some time with it.

**Comment by zfox23** [comment]
YAY! I would love to see some of your results, if you'd like to share. Enjoy!
